version: "3.9"
services:
  web:
    image: ricardoperovano/laravel
    container_name: web
    env_file:
      - ./app/.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    volumes:
      - ./app:/var/www/app
    networks:
      - app-network
    ports:
      - "8001:80" #http
      - "443:443" #https
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
